USE temp;
CREATE TABLE CUSTOMER(
id integer primary key,
name varchar (225),
address varchar (255),
gender char(2),
city varchar (255),
pincode integer
);


INSERT INTO CUSTOMER
VALUES(6789, 'Ted Lasso', 'Richmond', 'M', 'Richmond city', 432098);

INSERT INTO CUSTOMER
VALUES(1251, 'Ranjit Sharma', 'Kharangajhar', 'M', 'Tatanagar', 831004), 
      (5556, 'Tushar Shourie', 'New Town', 'M', 'Bangalore', 123456),
      (0709, 'Rupali Sharma', 'Mayur Vihar', 'F', 'New Delhi', 156789),
      (3107, 'Rahul Sharma', 'Indirapuram', 'M', 'Ghaziabad', 213456), 
      (0909, 'Amy Santiago', 'Brooklyn', 'F', 'New York', 111098), 
      (6789, 'Ted Lasso', 'Richmond', 'M', 'Richmond city', 432098);
      
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (id, name)
values(121, 'Bob');

-- Update
UPDATE CUSTOMER SET ADDRESS ='Mumbai', GENDER = 'M' WHERE ID =121;

-- update multiple rows
SET SQL_SAFE_UPDATES =0;
SET SQL_SAFE_UPDATES =1;
UPDATE CUSTOMER SET PINCODE = 110000;

UPDATE CUSTOMER SET PINCODE = PINCODE+ 1;

-- delete
DELETE FROM CUSTOMER WHERE ID = 121;

-- DELETE TABLE (FIRST SET SAFE MODE =0) THEN RUN THE BELOW COMMAND
DELETE FROM CUSTOMER;


CREATE TABLE ORDER_DETAILS(
ORDER_ID INT PRIMARY KEY,
DEL_DATE DATE,
CUST_ID INT,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) on delete SET NULL
);

SELECT * FROM ORDER_DETAILS;
DROP TABLE ORDER_DETAILS;

INSERT INTO order_details 
VALUES (3, '2023-06-19', 6789);

-- DELETES THE ROWS CORRESPONDING TO THE PARENT ROW DELETED BCOZ OF ON DELETE CASCADE
DELETE FROM CUSTOMER WHERE ID = 6789;

-- PUTS NULL IN CUST_ID AS THE PARENT TABLE ROW BEING REFERENCED IS DELETED BCOZ OF ON DELETE SET NULLL
DELETE FROM CUSTOMER WHERE ID = 6789;


-- replace
REPLACE INTO CUSTOMER (ID, CITY)
VALUES (6969, 'COLONY'); 

-- ANOTHER SYNTAX FOR REPLACE
REPLACE INTO CUSTOMER (ID, NAME, CITY)
SELECT ID, NAME, CITY FROM CUSTOMER WHERE ID = 3107;



