SELECT 55+14;

SELECT now();

SELECT ucase('TusHAr');

USE temp;
SHOW TABLES;

SELECT * FROM STUDENT;

CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
NAME VARCHAR(255) UNIQUE,
BALANCE INT NOT NULL DEFAULT 0
);

INSERT INTO ACCOUNT(ID, NAME, BALANCE)
VALUES(1, 'A', 10000);

INSERT INTO ACCOUNT(ID, NAME)
VALUES(2, 'B');

SELECT * FROM ACCOUNT;
DROP TABLE ACCOUNT;

-- ADD A NEW COLUMN
ALTER TABLE ACCOUNT ADD INTEREST FLOAT NOT NULL DEFAULT 0;

-- MODIFY A DATATYPE
ALTER TABLE ACCOUNT MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;

-- DESCRIBE 
DESC ACCOUNT;

-- DROP COLUMN
ALTER TABLE ACCOUNT DROP COLUMN SAVING_INT;


-- RENAME A COLUMN
ALTER TABLE ACCOUNT CHANGE COLUMN INTEREST SAVING_INT FLOAT NOT NULL DEFAULT 0;

-- RENAME A TABLE
ALTER TABLE ACCOUNT RENAME TO ACC_DETAILS;